### PR TITLE
Navbar

### PR DESCRIPTION
**Pull request by supriya1011**
navbar.html added successfully...

### CODE REVIEW

**Comment by Shreyashimaity** [comment]
Hello

**Comment by sudiptapramanik209** [comment]
function nobitaChange(N,str) {
    //write code here
    upp="ABCDEFGHIJKLMNOPQRSTUVWXYZ";
    low="abcdefghijklmnopqrstuvwxyz";
    let bag="";
    for(let j=0;j<=str.length-1;j++){
        let hero=str[j];
        let match="nahi mela";
        let bhai;
        for(let i=0;i<=low.length-1;i++){
        if(hero==upp[i]){
            match="bhi mil gaya";
            bhai=low[i];
            break;
        }
    }
    if(match=="nahi mela"){
        bag+=hero;
    }else{
        bag+=bhai;
    }


    }console.log(bag);
}

**Comment by sudiptapramanik209** [comment]
Sorry friend ma or kuch share karna cha Raha ta but mara cod share ho
gaya....plz delete kar dena....

**Comment by sudiptapramanik209** [comment]
function sumOfCornerColumns(N,M,arr){
    //write code here
    let row=arr.length;
    let col=arr[0].length;
    let sum=0;
    for(let i=0;i<col;i++){
        for(let j=0;j<row;j++){
            if(i==0||i==col-1){
                sum=sum+arr[j][i];
            }
        }
    }
    console.log(sum);
}

**Pull request merged**
